### PR TITLE
France ptt: 505 && 999 error codes

### PR DESCRIPTION
**Pull request by aderumier**
I'm not sure about the correct reasons, feel free to change it.

Currently in FrancePTT.pm, we have a lof of undef reason for retry later, I don't known if it could be improved ?

### CODE REVIEW

**Comment by azumakuniyuki** [comment]
Thanks for the Pull-Request.

It seems to hard to decide a bounce reason clearly because ...

## 1. OFR-505
```
<xxxx@wanadoo.fr>: host smtp-in.orange.fr[80.12.242.9] said: 421 4.2.0
    Service refuse. Veuillez essayer plus tard. Service refused, please try
    later. OFR005_505 [505] (in reply to end of DATA command)
```
The SMTP connection was rejected at **the end of DATA command**. It might have been rejected due to the content of one or more email header, or the message body. However, `4.2.0` indicates no clearly reason at https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/SMTP/Status.pm#L129-L131 . `421` is also unclear https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/SMTP/Reply.pm#L38-L40 .

The following are possible bounce reasons:

### A. `systemerror`
The mail server or a backend program is failed temporarily due to high load because the reply code and D.S.N. is 4XX. Sending message may be success at the next try.


### B. `filtered`
The connection was rejected due to an address filter or a content filter at checking email headers (rejected due to the value of From: header ?) or the message body. However, this is a temporary error (4XX). If the next SMTP connection is likely to succeed, it is not rejected by the content filter.

## 2. OFR-999
```
<xxxx@wanadoo.fr>: host smtp-in.orange.fr[193.252.22.65] refused to
    talk to me: 421 mwinf5c77 ME Service refuse. Veuillez essayer plus tard.
    Service refused, please try later. OFR_999 [999]
```

This error is also temporary error (4XX), but the error message does not include any SMTP command name.  Accordingly, the connection might be rejected at the SMTP greeting (before sending HELO/EHLO). 

The following are possible bounce reasons:

### A. `blocked`
It might be a mere temporary connection error.

### B. `toomanyconn`
It might be rejected due to too many concurrency connections from the same IP address.

**Comment by azumakuniyuki** [comment]
> Currently in FrancePTT.pm, we have a lof of undef reason for retry later, I don't known if it could be improved ?

Sample emails with undefined reason are welcome:-D because we have few samples returned from ESP in France and other European countries.

Best regards

**Comment by aderumier** [comment]
@azumakuniyuki 
for  OFR-999, I'm pretty sure It's because we are almost blacklisted, too much spam.
This is the worst level. 
I'm pretty sure it's not because of toomanyconn, as we limit to 2 connections. (they are very restrictive). So maybe "blocked" could be fine.

for OFR_505, I think it's more a systemerror. as I only have 2 samples on 24h (with more the 500k mails)


I'll try to get full explain for others code, we have a direct contact with the boss of orange.fr for the mailing service.

I'll send you sample of different error code if you need it, I think I can het them for almost all error code.

(BTW, the current FrancePTT module, is for 2 isp,  orange.fr (main french fai, with OFR_... code) and laposte.net (french postal compagny, with LPN_... code)  

Thanks again for your fast reply !

**Comment by azumakuniyuki** [comment]
> for OFR-999, I'm pretty sure It's because we are almost blacklisted, too much spam.
> This is the worst level.
> I'm pretty sure it's not because of toomanyconn, as we limit to 2 connections. (they are very restrictive). So maybe "blocked" could be fine.

Thank you for further information, I was convinced that the reason for OFR-999 was `blocked`.

> for OFR_505, I think it's more a systemerror. as I only have 2 samples on 24h (with more the 500k mails)

I will change the reason for OFR-505 to `systemerror` after merging this Pull-Request, Thanks :-)

> I'll try to get full explain for others code, we have a direct contact with the boss of orange.fr for the mailing service.
> I'll send you sample of different error code if you need it, I think I can het them for almost all error code.

I'm glad if you give these to us. Many sample emails and the error code list really make help Sisimai to be improved more and more. 

> (BTW, the current FrancePTT module, is for 2 isp, orange.fr (main french fai, with OFR_... code) and laposte.net (french postal compagny, with LPN_... code)

Isn't the name FrancePTT strange? ( Is the name FranchPTT more appropriate? )
we have looked for any mutual name with Orange and La Postes and have found a history described at https://en.wikipedia.org/wiki/La_Poste_(France)#History and decided as FrancePTT.

If you have more appropriate module name, we are glad to your suggestion.

Thanks again,

**Comment by aderumier** [comment]
@azumakuniyuki 

>>Isn't the name FrancePTT strange? ( Is the name FranchPTT more appropriate? )
>>we have looked for any mutual name with Orange and La Postes and have found a history >>described at https://en.wikipedia.org/wiki/La_Poste_(France)#History and decided as FrancePTT.

FrancePTT is ok, or FrenchPTT if you want, but not FranchPTT ;)
Indeed, 30years ago both company was same (postal and telephony), but they have been splitted, and are now private company.

Looking at errors code, it seem than they use almost same error code for same meaning, but the text
can be different.

I'll send a pull request today, with more errors code, and more descriptions. (I don't have all bounce emails sample, but I can already extract log from my postfix mailer)

**Comment by azumakuniyuki** [comment]
@aderumier 

> FrancePTT is ok, or FrenchPTT if you want, but not FranchPTT ;)

Thanks for the advise ! (FranchPTT was my mistake :-P )

> I'll send a pull request today, with more errors code, and more descriptions. (I don't have all bounce emails sample, but I can already extract log from my postfix mailer)

I'm waiting and look forward to receiving Pull-Request from you :-)

Best regards,

**Pull request merged**
